services:
  waf: 
    image: owasp/modsecurity-crs:nginx
    ports:
      - "8080:8080"
    environment:
      - BACKEND=http://m183-lb2-web:3000
      - PORT=8080
      - PARANOIA=2
      - MODSEC_RULE_ENGINE=On
    depends_on:
      web:
        condition: service_healthy
    networks:
      - app-network
  web:
    image: node:latest
    container_name: m183-lb2-web
    working_dir: /home/node/app
    user: node
    volumes:
      - ../aqq:/home/node/app
    command: sh -c "npm install && npm run start"
    environment:
      - DBSERVER=m183-lb2-db
      - DBUSER=root
      - DBPASSWORD=Some.Real.Secr3t
      - DBNAME=m183_lb2
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "--show-error", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    build: ./db
    container_name: m183-lb2-db
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=Some.Real.Secr3t
      - MARIADB_DATABASE=m183_lb2
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mariadb", "-uroot", "-pSome.Real.Secr3t", "-e", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge
